pre-commit:
  parallel: true
  commands:
    backend-erb-linter:
      glob: "app/views/**/*.html.erb"
      run: |
        docker-compose run --rm web bash -c "script/format_erb.sh {staged_files}"
        LINT_EXIT_CODE=$?
        echo "ERB Lint finished with exit code $LINT_EXIT_CODE."
        exit $LINT_EXIT_CODE
      stage_fixed: true